kind: pipeline
type: docker
name: Build and Upload

workspace:
  base: /go
  path: src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
  
trigger:
  event:
  - push

steps:
- name: build
  image: golang
  commands:
  - mkdir data
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go build -o mobile-node-remote-client .
  - chmod +x mobile-node-remote-client
 
- name: upload
  image: plugins/s3
  settings:
    bucket: lambda-devops-use-only
    region: us-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: mobile-node-remote-client
    target: /magicleap/LMRC/latest/
    acl: public-read
